### PR TITLE
fix infinite alert after game is over

### LINKED ISSUE #1: 🐞 Infinite alert loop during gameover
When the game is over, the alert box saying "game over" shows up & it goes into an infinite loop.

Some hints:
- [x] Search for `game over` in javascript file to know where to start
- [ ] Try to understand the root cause of the issue by using debugger points
- [ ] Comment on this issue to discuss how you're going to fix it before creating a PR
- [ ] Create a PR with the fix

Look the repo for live link to play the game & contributing guidelines
https://github.com/PezCoder/Mr.Snake

### PR DESCRIPTION
**Pull request by masquel**
fix #1 issue

### CODE REVIEW

**Comment by PezCoder** [comment]
Did you tried it out ? Unfortunately this is still opening multiple alert popups after game is over.

Here is a suggestion:
1. Introduce a new variable named `gameOver = false`
2. Modify `lives === 0` check to `lives === 0 && !gameOver`, so we show the alert only when the game is not over yet.
3. Set `gameOver = true` inside the above check so that in the next tick of game loop, it doesn't enter this condition, hence no multiple alerts 😄

**Comment by masquel** [comment]
Yes, i tried it in chrome 61.0.3163.100, firefox 56.0 and everything is ok.

**Comment by PezCoder** [comment]
This is working perfectly.. !
Just one last thing, Don't you think it would be better to put `alert("Game Over !! :( ");` instruction inside the new `gameOver` function so that we have everything related to end game in that one single function ?

**Comment by masquel** [comment]
Done.

**Comment by PezCoder** [comment]
You can see your changes here: @masquel 
http://pezcoder.github.io/Mr.Snake/snake.html

Thank you for working on this 👏🏼

**Pull request merged**
